# Generated by Django 6.0.5 on 2026-05-05 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('codigo_estudiante', models.CharField(max_length=50, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo_institucional', models.EmailField(max_length=200, unique=True)),
                ('carrera', models.CharField(blank=True, max_length=150, null=True)),
                ('foto_estudiante_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_frontal_url', models.TextField(blank=True, null=True)),
                ('foto_respaldo_url', models.TextField(blank=True, null=True)),
                ('codigo_qr', models.CharField(max_length=200, unique=True)),
                ('estado_actual', models.CharField(choices=[('ADENTRO', 'Adentro'), ('AFUERA', 'Afuera')], default='AFUERA', max_length=10)),
                ('estudiante', models.ForeignKey(db_column='cc_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='core.estudiante')),
            ],
            options={
                'db_table': 'dispositivo',
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.dispositivo')),
            ],
            options={
                'db_table': 'historial_movimientos',
            },
        ),
    ]
