# Generated by Django 6.0.5 on 2026-05-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
